QUESTION_BANK = {
    "Biology": {
        "Cell Division": {
            "easy": [
                {"q": "What is mitosis?",
                 "a": "Mitosis is cell division that produces two genetically identical daughter cells from one parent cell."},
                {"q": "What are the four phases of mitosis?",
                 "a": "Prophase, metaphase, anaphase, and telophase."},
                {"q": "What is the purpose of cell division?",
                 "a": "Cell division allows organisms to grow, repair tissues, and reproduce."},
                {"q": "What is a chromosome?",
                 "a": "A chromosome is a structure of DNA and proteins that carries genetic information."},
                {"q": "What happens during cytokinesis?",
                 "a": "The cytoplasm divides, producing two separate daughter cells."},
                {"q": "What is the cell cycle?",
                 "a": "The cell cycle is the series of events a cell goes through as it grows and divides."},
            ],
            "medium": [
                {"q": "Compare mitosis and meiosis.",
                 "a": "Mitosis produces 2 identical diploid cells for growth; meiosis produces 4 genetically unique haploid cells for sexual reproduction."},
                {"q": "What happens during the S phase of the cell cycle?",
                 "a": "DNA replication occurs, creating two copies of each chromosome."},
                {"q": "Why is the G1 checkpoint important?",
                 "a": "It ensures the cell is large enough and DNA is undamaged before committing to division."},
                {"q": "What are sister chromatids?",
                 "a": "The two identical copies of a chromosome joined at the centromere after DNA replication."},
                {"q": "What is the role of the spindle fibers?",
                 "a": "Spindle fibers attach to chromosomes and pull them apart to opposite poles during anaphase."},
            ],
            "hard": [
                {"q": "How can mutations in cell cycle regulators lead to cancer?",
                 "a": "Mutations in genes like p53 or cyclins disable checkpoints that stop damaged cells from dividing, causing uncontrolled growth."},
                {"q": "How do spindle fiber errors lead to aneuploidy?",
                 "a": "If spindle fibers fail to separate chromosomes correctly during anaphase, daughter cells receive the wrong chromosome number."},
                {"q": "Describe the role of cyclin-CDK complexes in the cell cycle.",
                 "a": "Cyclins bind CDKs, activating them to phosphorylate proteins that drive the cell through key checkpoints."},
                {"q": "How does contact inhibition prevent healthy cells from over-dividing?",
                 "a": "When cells contact neighbors, signaling pathways suppress division. Cancer cells lose this inhibition and divide uncontrollably."},
                {"q": "What is apoptosis and why is it important for cell cycle regulation?",
                 "a": "Apoptosis is programmed cell death. It eliminates damaged or abnormal cells before they can become cancerous."},
            ],
        },
        "Photosynthesis": {
            "easy": [
                {"q": "What is photosynthesis?",
                 "a": "Photosynthesis is how plants use sunlight, water, and CO₂ to produce glucose and oxygen."},
                {"q": "What is the overall equation for photosynthesis?",
                 "a": "6CO₂ + 6H₂O + light energy → C₆H₁₂O₆ + 6O₂"},
                {"q": "Where does photosynthesis take place in the cell?",
                 "a": "In the chloroplasts of plant cells."},
                {"q": "What pigment absorbs light for photosynthesis?",
                 "a": "Chlorophyll is the main light-absorbing pigment."},
                {"q": "What are the two main stages of photosynthesis?",
                 "a": "The light-dependent reactions (thylakoids) and the Calvin cycle (stroma)."},
                {"q": "What gas do plants release during photosynthesis?",
                 "a": "Oxygen (O₂) is released as a byproduct."},
            ],
            "medium": [
                {"q": "What is produced during the light-dependent reactions?",
                 "a": "ATP, NADPH, and oxygen (from splitting water)."},
                {"q": "Explain the role of NADPH in the Calvin cycle.",
                 "a": "NADPH provides electrons used to reduce CO₂ into glucose (G3P) in the Calvin cycle."},
                {"q": "Why do plants appear green?",
                 "a": "Chlorophyll absorbs red and blue light but reflects green light."},
                {"q": "What is the role of stomata in photosynthesis?",
                 "a": "Stomata are leaf pores that allow CO₂ in and O₂ out during photosynthesis."},
                {"q": "What is RuBisCO and what does it do?",
                 "a": "RuBisCO is the enzyme that captures CO₂ and begins the Calvin cycle."},
            ],
            "hard": [
                {"q": "How does the electron transport chain work in the light reactions?",
                 "a": "Excited electrons pass through membrane proteins, releasing energy that pumps H⁺ ions to generate ATP via ATP synthase."},
                {"q": "What is photorespiration and why is it a problem for C3 plants?",
                 "a": "When RuBisCO binds O₂ instead of CO₂, energy is wasted without producing sugar — reducing photosynthetic efficiency."},
                {"q": "Compare C3, C4, and CAM photosynthesis.",
                 "a": "C3 fixes CO₂ directly; C4 concentrates CO₂ in bundle sheath cells; CAM plants fix CO₂ at night to minimize water loss."},
                {"q": "How does the chemiosmotic gradient drive ATP synthesis?",
                 "a": "H⁺ ions build up in the thylakoid lumen; their flow back through ATP synthase releases energy to phosphorylate ADP to ATP."},
                {"q": "Why is the Calvin cycle called a cycle?",
                 "a": "Because the starting molecule (RuBP) is regenerated at the end, allowing continuous CO₂ fixation."},
            ],
        },
        "DNA and Genetics": {
            "easy": [
                {"q": "What does DNA stand for?",
                 "a": "Deoxyribonucleic acid."},
                {"q": "What are the four nitrogenous bases in DNA?",
                 "a": "Adenine (A), Thymine (T), Guanine (G), and Cytosine (C)."},
                {"q": "What is a gene?",
                 "a": "A gene is a segment of DNA that codes for a specific protein or trait."},
                {"q": "What is a dominant allele?",
                 "a": "A dominant allele is expressed in the phenotype even when only one copy is present."},
                {"q": "What is the difference between genotype and phenotype?",
                 "a": "Genotype is the genetic makeup; phenotype is the observable physical traits."},
                {"q": "What is DNA replication?",
                 "a": "The process by which a cell copies its DNA before cell division."},
            ],
            "medium": [
                {"q": "State Mendel's law of segregation.",
                 "a": "During gamete formation, the two alleles for each trait separate so each gamete carries only one allele."},
                {"q": "What is the central dogma of molecular biology?",
                 "a": "DNA is transcribed into mRNA, which is translated into a protein: DNA → RNA → Protein."},
                {"q": "What is codominance? Give an example.",
                 "a": "Both alleles are fully expressed. Example: AB blood type shows both A and B antigens."},
                {"q": "What is the difference between transcription and translation?",
                 "a": "Transcription copies DNA into mRNA in the nucleus; translation uses mRNA to build a protein at the ribosome."},
                {"q": "What is a Punnett square?",
                 "a": "A grid used to predict the probability of offspring inheriting specific genotypes or phenotypes."},
            ],
            "hard": [
                {"q": "How does a frameshift mutation differ from a point mutation?",
                 "a": "A point mutation changes one base; a frameshift inserts or deletes bases, shifting the reading frame and altering all downstream amino acids — usually more damaging."},
                {"q": "How does CRISPR-Cas9 edit genes?",
                 "a": "A guide RNA directs Cas9 to a specific DNA sequence; Cas9 cuts both strands, and the cell's repair machinery introduces the desired change."},
                {"q": "What is epigenetics?",
                 "a": "Epigenetics involves chemical modifications (like methylation) that alter gene expression without changing the DNA sequence."},
                {"q": "How does meiosis produce genetic variation?",
                 "a": "Crossing over exchanges chromosome segments during meiosis I; independent assortment randomly distributes maternal and paternal chromosomes — together they create vast diversity."},
                {"q": "Explain X-linked inheritance and why it affects males more often.",
                 "a": "X-linked traits are on the X chromosome. Males (XY) have only one X, so a single recessive allele is expressed. Females (XX) need two copies to show the trait."},
            ],
        },
    },
    "Math": {
        "Algebra": {
            "easy": [
                {"q": "What is a variable in algebra?",
                 "a": "A symbol (usually a letter) that represents an unknown value."},
                {"q": "Solve for x: x + 5 = 12",
                 "a": "x = 7"},
                {"q": "What is the order of operations (PEMDAS)?",
                 "a": "Parentheses, Exponents, Multiplication/Division (left to right), Addition/Subtraction (left to right)."},
                {"q": "Simplify: 2x + 3x",
                 "a": "5x"},
                {"q": "What is a coefficient?",
                 "a": "The numerical factor multiplied by a variable (e.g., in 3x the coefficient is 3)."},
                {"q": "Evaluate 4x - 2 when x = 3.",
                 "a": "4(3) - 2 = 12 - 2 = 10"},
            ],
            "medium": [
                {"q": "Solve for x: 2x - 4 = 10",
                 "a": "2x = 14, so x = 7"},
                {"q": "What is slope-intercept form?",
                 "a": "y = mx + b, where m is the slope and b is the y-intercept."},
                {"q": "Factor: x² - 9",
                 "a": "(x + 3)(x - 3) — difference of squares."},
                {"q": "What does it mean to solve a system of equations?",
                 "a": "Finding values for the variables that satisfy all equations simultaneously. Methods: substitution, elimination, or graphing."},
                {"q": "Solve: 3(x + 2) = 21",
                 "a": "3x + 6 = 21 → 3x = 15 → x = 5"},
            ],
            "hard": [
                {"q": "Solve: x² - 5x + 6 = 0",
                 "a": "Factor: (x-2)(x-3) = 0, so x = 2 or x = 3."},
                {"q": "What is the discriminant and what does it tell you?",
                 "a": "b²-4ac. If > 0: two real roots; if = 0: one real root; if < 0: no real roots (complex)."},
                {"q": "What is function composition? Give an example.",
                 "a": "Applying one function to the result of another. If f(x)=2x and g(x)=x+1, then f(g(x))=2(x+1)=2x+2."},
                {"q": "Prove the sum of two odd numbers is always even.",
                 "a": "Odd numbers are 2k+1 and 2m+1. Their sum = 2k+2m+2 = 2(k+m+1), which is divisible by 2."},
                {"q": "Simplify: (x² - 4) / (x - 2)",
                 "a": "Factor numerator: (x+2)(x-2)/(x-2) = x+2, for x ≠ 2."},
            ],
        },
        "Geometry": {
            "easy": [
                {"q": "What is the perimeter of a rectangle with length 8 and width 5?",
                 "a": "P = 2(8+5) = 26"},
                {"q": "What are the three types of triangles by angle?",
                 "a": "Acute (all angles < 90°), right (one 90° angle), obtuse (one angle > 90°)."},
                {"q": "What is the area of a triangle with base 10 and height 6?",
                 "a": "A = ½ × 10 × 6 = 30"},
                {"q": "State the Pythagorean theorem.",
                 "a": "In a right triangle: a² + b² = c², where c is the hypotenuse."},
                {"q": "What is the circumference of a circle with radius 7? (π ≈ 3.14)",
                 "a": "C = 2πr = 2 × 3.14 × 7 ≈ 43.96"},
                {"q": "How many degrees are in a straight line?",
                 "a": "180 degrees."},
            ],
            "medium": [
                {"q": "What is the sum of interior angles of a pentagon?",
                 "a": "(5-2) × 180 = 540°"},
                {"q": "What does it mean for two triangles to be congruent?",
                 "a": "All corresponding sides and angles are equal — they are the same shape and size."},
                {"q": "Find the area of a circle with diameter 10.",
                 "a": "r = 5, A = πr² = 25π ≈ 78.54"},
                {"q": "What is the difference between similar and congruent figures?",
                 "a": "Similar figures have the same shape but different sizes; congruent figures are identical in shape and size."},
                {"q": "A right triangle has legs of 6 and 8. What is the hypotenuse?",
                 "a": "c² = 36 + 64 = 100, so c = 10."},
            ],
            "hard": [
                {"q": "Prove that the base angles of an isosceles triangle are equal.",
                 "a": "Draw the altitude from the apex. It creates two congruent right triangles (same height, equal legs by definition), so by SAS the base angles are equal."},
                {"q": "A ladder 13 ft long leans against a wall with its base 5 ft away. How high does it reach?",
                 "a": "h² + 25 = 169 → h² = 144 → h = 12 ft."},
                {"q": "What is the volume of a cone with radius 3 and height 4?",
                 "a": "V = ⅓πr²h = ⅓ × π × 9 × 4 = 12π ≈ 37.7"},
                {"q": "Explain why a tangent line is perpendicular to the radius at the point of tangency.",
                 "a": "The shortest distance from the center to the tangent line is the radius. The shortest distance from a point to a line is always perpendicular to that line."},
                {"q": "What is the surface area of a sphere with radius 5?",
                 "a": "SA = 4πr² = 4π(25) = 100π ≈ 314.16"},
            ],
        },
    },
    "History": {
        "World War II": {
            "easy": [
                {"q": "When did World War II begin and end?",
                 "a": "It began in 1939 (Germany's invasion of Poland) and ended in 1945."},
                {"q": "Who were the Allied Powers?",
                 "a": "The major Allied Powers were the United States, United Kingdom, France, and the Soviet Union."},
                {"q": "What event brought the US into World War II?",
                 "a": "Japan's attack on Pearl Harbor on December 7, 1941."},
                {"q": "Who was the leader of Nazi Germany?",
                 "a": "Adolf Hitler."},
                {"q": "What was D-Day?",
                 "a": "The Allied invasion of Normandy, France on June 6, 1944 — the largest amphibious operation in history."},
                {"q": "What were the Axis Powers?",
                 "a": "Germany, Italy, and Japan."},
            ],
            "medium": [
                {"q": "What was the Holocaust?",
                 "a": "The systematic murder of approximately six million Jews and millions of others by the Nazi regime."},
                {"q": "What was the significance of the Battle of Stalingrad?",
                 "a": "Germany's defeat (1942-43) was a turning point — it ended the German advance into the Soviet Union."},
                {"q": "What were the main causes of World War II?",
                 "a": "The Treaty of Versailles, the Great Depression, the rise of fascism, and failed appeasement policies."},
                {"q": "What were the Nuremberg Trials?",
                 "a": "Post-war tribunals (1945-46) that prosecuted Nazi leaders for war crimes and crimes against humanity."},
                {"q": "What was Lend-Lease?",
                 "a": "A US program that supplied Allied nations with food, oil, and war materials before and during US involvement in the war."},
            ],
            "hard": [
                {"q": "How did the Treaty of Versailles contribute to Hitler's rise?",
                 "a": "It imposed massive reparations, stripped Germany of territory, and assigned war guilt — creating economic hardship and national humiliation that Hitler exploited for popular support."},
                {"q": "How did atomic weapons change the nature of warfare after WWII?",
                 "a": "They created mutually assured destruction (MAD), shifting conflicts to proxy wars and making direct superpower confrontation catastrophically risky."},
                {"q": "Compare Germany's Blitzkrieg with Allied counter-strategies.",
                 "a": "Blitzkrieg used rapid armored advances with air support. Allies countered with industrial mobilization, Lend-Lease supply chains, and multi-front pressure that stretched German resources."},
                {"q": "What role did propaganda play in WWII?",
                 "a": "Propaganda shaped opinion, dehumanized enemies, and boosted morale. Germany used it to scapegoat minorities; the US used it for war bonds and enlistment; the UK used it to sustain civilian resolve during the Blitz."},
                {"q": "Why did the Soviet Union suffer the most casualties in WWII?",
                 "a": "The Eastern Front was the largest land war in history; Nazi ideology targeted Slavic people; the Soviet Union bore the brunt of German invasion with massive military and civilian losses (estimated 27 million dead)."},
            ],
        },
        "Civil Rights Movement": {
            "easy": [
                {"q": "What was the Civil Rights Movement?",
                 "a": "A struggle in the 1950s-60s to end racial segregation and discrimination against African Americans in the US."},
                {"q": "Who was Rosa Parks?",
                 "a": "A civil rights activist who refused to give up her bus seat in 1955, sparking the Montgomery Bus Boycott."},
                {"q": "What was the 'I Have a Dream' speech?",
                 "a": "Martin Luther King Jr.'s 1963 speech at the March on Washington, calling for racial equality."},
                {"q": "What did the Civil Rights Act of 1964 do?",
                 "a": "It outlawed discrimination based on race, color, religion, sex, or national origin in employment and public accommodations."},
                {"q": "What were Jim Crow laws?",
                 "a": "State laws enforcing racial segregation in the American South from the 1870s to 1960s."},
                {"q": "What was the Montgomery Bus Boycott?",
                 "a": "A 381-day protest in which African Americans refused to ride Montgomery, Alabama buses to challenge segregated seating."},
            ],
            "medium": [
                {"q": "What was the significance of Brown v. Board of Education?",
                 "a": "The 1954 Supreme Court ruling declared racial segregation in public schools unconstitutional."},
                {"q": "Why were nonviolent tactics effective in the Civil Rights Movement?",
                 "a": "Sit-ins, marches, and boycotts drew national attention to injustice, built moral authority, and pressured lawmakers to act."},
                {"q": "What was the Voting Rights Act of 1965?",
                 "a": "It prohibited discriminatory voting practices like literacy tests that had disenfranchised Black voters across the South."},
                {"q": "How did Malcolm X's approach differ from Martin Luther King Jr.'s?",
                 "a": "Malcolm X (initially) advocated Black self-defense and separatism; King advocated nonviolent integration. They represented a broader spectrum of civil rights strategy."},
                {"q": "What was the role of SNCC in the Civil Rights Movement?",
                 "a": "The Student Nonviolent Coordinating Committee organized youth-led sit-ins, voter registration drives, and later pushed toward Black Power ideology."},
            ],
            "hard": [
                {"q": "How did the Cold War shape the US government's response to the Civil Rights Movement?",
                 "a": "Racial injustice undermined US credibility as a democracy against the Soviet Union, giving civil rights leaders political leverage — the government had incentive to reform its international image."},
                {"q": "Analyze the economic dimensions of the Civil Rights Movement.",
                 "a": "Economic exploitation (sharecropping, wage discrimination, exclusion from unions) was central. Boycotts used economic pressure directly; broader goals included equal employment and fair wages."},
                {"q": "How did television transform the Civil Rights Movement?",
                 "a": "TV broadcast images of police violence against peaceful protesters into American homes, shifting public sympathy toward activists and pressuring politicians to act on legislation."},
                {"q": "Compare the strategies of SNCC, SCLC, and the NAACP.",
                 "a": "NAACP focused on legal challenges; SCLC organized mass nonviolent protest (King); SNCC was youth-led and later pushed Black Power under Stokely Carmichael. All pursued civil rights through different means."},
                {"q": "Why is the Civil Rights Movement considered unfinished by many historians?",
                 "a": "Legal victories did not fully address systemic economic inequality, housing discrimination, or mass incarceration. Racial disparities in wealth, education, and justice persist today."},
            ],
        },
    },
    "Computer Science": {
        "Python Basics": {
            "easy": [
                {"q": "What is a variable in Python?",
                 "a": "A named storage location for a value (e.g., x = 5 stores 5 in a variable named x)."},
                {"q": "What does print() do in Python?",
                 "a": "It outputs text or values to the console."},
                {"q": "What is the difference between an integer and a float?",
                 "a": "An integer is a whole number (e.g., 5); a float is a decimal number (e.g., 5.0)."},
                {"q": "What is an if statement?",
                 "a": "A conditional that executes a block of code only when a specified condition is True."},
                {"q": "What is a Python list?",
                 "a": "An ordered, mutable collection of items (e.g., [1, 2, 3])."},
                {"q": "How do you get the length of a list in Python?",
                 "a": "Use len(list_name). Example: len([1, 2, 3]) returns 3."},
            ],
            "medium": [
                {"q": "What is the difference between a list and a tuple?",
                 "a": "Lists are mutable (changeable after creation); tuples are immutable (cannot be changed)."},
                {"q": "What does a for loop do?",
                 "a": "It iterates over a sequence and executes a block of code for each element."},
                {"q": "How do you define a function in Python?",
                 "a": "Use: def function_name(parameters): followed by the indented function body."},
                {"q": "What is a Python dictionary? Give an example.",
                 "a": "A collection of key-value pairs. Example: {'name': 'Alice', 'age': 25}"},
                {"q": "What is the difference between == and = in Python?",
                 "a": "= assigns a value to a variable; == compares two values for equality."},
            ],
            "hard": [
                {"q": "What is the difference between a shallow copy and a deep copy?",
                 "a": "A shallow copy creates a new object but references the same nested objects; a deep copy recursively copies all nested objects. Use copy.deepcopy() for deep copies."},
                {"q": "How does list comprehension work? Give an example.",
                 "a": "[expr for item in iterable if condition]. Example: [x**2 for x in range(5)] → [0, 1, 4, 9, 16]."},
                {"q": "What is a decorator in Python?",
                 "a": "A function that wraps another function to extend its behavior. Applied with @decorator_name above a function definition."},
                {"q": "Write a recursive function to compute factorial.",
                 "a": "def factorial(n): return 1 if n <= 1 else n * factorial(n-1)"},
                {"q": "What is the difference between *args and **kwargs?",
                 "a": "*args collects extra positional arguments into a tuple; **kwargs collects extra keyword arguments into a dictionary."},
            ],
        },
        "Data Structures": {
            "easy": [
                {"q": "What is a stack?",
                 "a": "A data structure following Last In First Out (LIFO) order — the last item added is the first removed."},
                {"q": "What is a queue?",
                 "a": "A data structure following First In First Out (FIFO) order — the first item added is the first removed."},
                {"q": "What is an array?",
                 "a": "A collection of elements stored at contiguous memory locations, accessed by index."},
                {"q": "What is a linked list?",
                 "a": "A sequence of nodes where each node stores data and a reference (pointer) to the next node."},
                {"q": "What is the difference between a stack and a queue?",
                 "a": "A stack removes the most recently added item (LIFO); a queue removes the oldest item (FIFO)."},
                {"q": "What is a tree data structure?",
                 "a": "A hierarchical structure with a root node and child nodes, where each node has at most one parent."},
            ],
            "medium": [
                {"q": "What is a binary search tree (BST)?",
                 "a": "A tree where each node's left child has a smaller value and right child has a larger value, enabling efficient O(log n) search."},
                {"q": "What is the time complexity of searching an unsorted list?",
                 "a": "O(n) — you may need to check every element."},
                {"q": "What is a hash table and why is it useful?",
                 "a": "A hash table maps keys to values using a hash function, giving O(1) average-case lookup, insertion, and deletion."},
                {"q": "What is the difference between BFS and DFS?",
                 "a": "BFS explores all neighbors before going deeper (uses a queue); DFS explores as far as possible along a branch before backtracking (uses a stack or recursion)."},
                {"q": "What is the time complexity of binary search?",
                 "a": "O(log n) — each comparison eliminates half the remaining elements."},
            ],
            "hard": [
                {"q": "Explain the difference between a min-heap and a max-heap.",
                 "a": "In a min-heap the parent is always smaller (smallest at root); in a max-heap the parent is always larger (largest at root). Both support O(log n) insert and removal."},
                {"q": "How can a graph be represented in code?",
                 "a": "As an adjacency matrix (2D array, fast edge lookup) or adjacency list (dict of lists, space-efficient for sparse graphs)."},
                {"q": "What is dynamic programming? Give an example.",
                 "a": "Breaking problems into overlapping subproblems and caching results to avoid redundant computation. Examples: Fibonacci sequence, longest common subsequence, 0/1 knapsack."},
                {"q": "Explain amortized time complexity using a dynamic array as an example.",
                 "a": "Most appends are O(1), but occasional resizing is O(n). Spreading the resize cost across all appends gives O(1) amortized cost per operation."},
                {"q": "What is a trie and when is it useful?",
                 "a": "A trie is a tree where each node represents a character. It enables O(m) string search/insert (m = word length) — ideal for autocomplete and spell-checking."},
            ],
        },
    },
}
